% =========================================================================
% Practical 2: Mandelbrot-Set Serial vs Parallel Analysis
% =========================================================================
%
% GROUP NUMBER:
%
% MEMBERS:
%   - Alex Hillman, HLLALE010
%   - Joab Kloppers, KLPJOA002

%% ========================================================================
%  PART 4: Testing and Analysis
%  ========================================================================
% Compare the performance of serial Mandelbrot set computation
% with parallel Mandelbrot set computation.

function run_analysis()
    %Array conatining all the image sizes to be tested
    image_sizes = [
        [800,600],   %SVGA
        [1280,720],  %HD
        [1920,1080], %Full HD
        [2048,1080], %2K Cinema
        [2560,1440], %2K QHD
        [3840,2160], %4K UHD
        [5120,2880], %5K
        [7680,4320]  %8K UHD
    ];

    max_iterations = 1000; 

    %mandelbrot_serial(max_iterations,image_sizes,10);
    mandelbrot_parallel(max_iterations,image_sizes,10,12);
    %mandelbrot_GPU(max_iterations,image_sizes,3);
    
    %TODO: For each image size, perform the following:
    %   a. Measure execution time of mandelbrot_serial
    %   b. Measure execution time of mandelbrot_parallel
    %   c. Store results (image size, time_serial, time_parallel, speedup)  
    %   d. Plot and save the Mandelbrot set images generated by both methods
    
end

%% ========================================================================
%  PART 1: Mandelbrot Set Image Plotting and Saving
%  ========================================================================
%
% TODO: Implement Mandelbrot set plotting and saving function
function mandelbrot_plot(iter_map,size,max_iter,folder,other) %Add necessary input arguments
    
    image_Size_Names = ["800x600_SVGA","1280x720_HD","1920x1080_Full_HD","2048x1080_2K","2560x1440_QHD","3840x2160_4K","5120x2880_5K","7680x4320_8K"];

    % Normalize iter_map to [0, 255] for image output iter_map
    img_normalized = uint8(255 * iter_map ./max_iter);
        
    % Apply a colormap 
    cmap = hot(256);
    img_rgb = ind2rgb(img_normalized, cmap);
        
    % Save to file
    filename = folder+"/mandelbrot_"+image_Size_Names(size)+other+".png";
    imwrite(img_rgb,filename);
    fprintf("Written\n\n")

    %end
end

%% ========================================================================
%  PART 2: Serial Mandelbrot Set Computation
%  ========================================================================`
%
%TODO: Implement serial Mandelbrot set computation function
function mandelbrot_serial(max_iter,sizes,iterations) 
    image_Size_Names = ["800x600_SVGA","1280x720_HD","1920x1080_Full_HD","2048x1080_2K","2560x1440_QHD","3840x2160_4K","5120x2880_5K","7680x4320_8K"];

    % Build headers
    iterHeaders = arrayfun(@(i) sprintf('Iter_%d', i), 1:iterations, 'UniformOutput', false);
    headers = [{'ImageSize'}, iterHeaders];
    
    % Preallocate rows
    numRows = numel(image_Size_Names);
    dataRows = cell(numRows, 1 + iterations);

    %initialise the time average variable and result row counter value
    Times = zeros(length(iterations));
    result_row = 1;
    
    % run though the different image sizes
    for i = 1:length(sizes)
        fprintf(image_Size_Names(i)+"\n");

        width = sizes(i,1);
        height = sizes(i,2);
        % Define the region of the complex plane to view
        x_range = linspace(-2.5, 0.5, width);   % Real axis
        y_range = linspace(-1.2, 1.2, height);  % Imaginary axis
    
        % Preallocate output image (each pixel = iteration count)
        iter_map = zeros(height, width);
        
        %repeat mandelbrot image several times for averaging
        for repeat = 1:iterations

            tic;
        
            %Loop over every pixel 
            for row = 1:height
                for col = 1:width
                    x0 = x_range(col);
                    y0 = y_range(row);
        
                    x = 0;
                    y = 0;
                    iteration = 0;
        
                    % Get iteration number for pixel
                    while iteration < max_iter && (x^2 + y^2) <= 4
                        x_next = x^2 - y^2 + x0; 
                        y_next = 2*x*y + y0;
        
                        x = x_next;
                        y = y_next;
                        iteration = iteration + 1;
                    end
                    
                    iter_map(row, col) = iteration;
                end
            end
    
            Times(repeat) = toc;
            %plot the last generated image
            if repeat == iterations
                mandelbrot_plot(iter_map,i,max_iter,"Images_Serial","");
            end

        end
        %store the results into the table
        dataRows(result_row, :) = [{image_Size_Names(i)}, num2cell(Times)];
        result_row = result_row + 1;
        
    end
    output = [headers; dataRows];
    writecell(output, "Serial_Times.csv");
end

%% ========================================================================
%  PART 3: Parallel Mandelbrot Set Computation
%  ========================================================================
%
%TODO: Implement parallel Mandelbrot set computation function
function mandelbrot_parallel(max_iter,sizes,iterations,max_threads) %Add necessary input arguments 

    coreCounts = 1:max_threads;
    image_Size_Names = ["800x600_SVGA","1280x720_HD","1920x1080_Full_HD","2048x1080_2K","2560x1440_QHD","3840x2160_4K","5120x2880_5K","7680x4320_8K"];
    
    % Build headers
    iterHeaders = arrayfun(@(i) sprintf('Iter_%d', i), 1:iterations, 'UniformOutput', false);
    headers = [{'Cores', 'ImageSize'}, iterHeaders];
    
    % Preallocate rows
    numRows = numel(coreCounts) * numel(image_Size_Names);
    dataRows = cell(numRows, 2 + iterations);

    %initialise the time average variable and result row counter value    
    Times = zeros(length(iterations));
    result_row = 1;

    %Iterate through the given number of processing cores.
    for c = 2:max_threads
        
        %create the parallel pool
        poolobj = gcp('nocreate');
        if isempty(poolobj)
            parpool('local',c);
        end
    
        %iterate through all the image sizes
        for i = 1:length(sizes)
            fprintf(image_Size_Names(i)+"\n");

            width = sizes(i,1);
            height = sizes(i,2);
            % Define the region of the complex plane to view
            x_range = linspace(-2.5, 0.5, width);   % Real axis
            y_range = linspace(-1.2, 1.2, height);  % Imaginary axis
        
            % Preallocate output image
            iter_map = zeros(height, width);
        
            %Repeat through the number of iterations for averaging
            for repeat = 1:iterations
    
                tic;
            
                %Loop over every pixel

                %use parallel for loop on the outer loop, this essentially
                %splits up the rows across the number of workers.
                parfor row = 1:height
                    for col = 1:width
                        x0 = x_range(col);
                        y0 = y_range(row);
            
                        x = 0;
                        y = 0;
                        iteration = 0;
            
                        % Core Mandelbrot loop
                        while iteration < max_iter && (x^2 + y^2) <= 4
                            x_next = x^2 - y^2 + x0;
                            y_next = 2*x*y + y0;
            
                            x = x_next;
                            y = y_next;
                            iteration = iteration + 1;
                        end
            
                        iter_map(row, col) = iteration;
                    end
                end
        
                Times(repeat) = toc;

                %plot the last iteration and stor the image
                if repeat == iterations 
                    mandelbrot_plot(iter_map,i,max_iter,"Images_Parallel","_"+c+"cores");
                end
            end
            
            %store results into dataRows table
            dataRows(result_row, :) = [{c}, {image_Size_Names(i)}, num2cell(Times)];
            result_row = result_row + 1;
        end

        delete(gcp('nocreate'));

    end

    output = [headers; dataRows];
    writecell(output, 'Parallel_benchmark_results.csv');

end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Side experiment to check GPU performance.
function mandelbrot_GPU(max_iter, sizes, iterations)
    image_Size_Names = ["800x600_SVGA","1280x720_HD","1920x1080_Full_HD","2048x1080_2K","2560x1440_QHD","3840x2160_4K","5120x2880_5K","7680x4320_8K"];
    
    % Build headers
    iterHeaders = arrayfun(@(i) sprintf('Iter_%d', i), 1:iterations, 'UniformOutput', false);
    headers = [{'ImageSize'}, iterHeaders];
    
    Times = zeros(length(iterations));

    % Preallocate rows
    numRows = numel(image_Size_Names);
    dataRows = cell(numRows, 1 + iterations);

    result_row = 1;
    for i = 1:length(sizes)
        fprintf(image_Size_Names(i) + "\n");

        width  = sizes(i, 1);
        height = sizes(i, 2);
        x_range_gpu = gpuArray(linspace(-2.5, 0.5, width));
        y_range_gpu = gpuArray(linspace(-1.2, 1.2, height));

        %spread out the pixels across the GPU space
        [X0, Y0] = meshgrid(x_range_gpu, y_range_gpu);

        for repeat = 1:iterations
            X        = zeros(height, width, 'single', 'gpuArray');
            Y        = zeros(height, width, 'single', 'gpuArray');
            iter_map = zeros(height, width, 'single', 'gpuArray');
            escaped  = false(height, width, 'gpuArray');   % ← persistent latch
            tic;
            
            %get the iteration count for every pixel using GPU
            for k = 1:max_iter
                % Check escape on CURRENT values, before any update
                escaped     = escaped | (X.^2 + Y.^2 > 4);
                still_inside = ~escaped;

                X_new = X.^2 - Y.^2 + X0;
                Y_new = 2.*X.*Y + Y0;

                % Only update pixels still inside
                X = X_new .* still_inside + X .* escaped;
                Y = Y_new .* still_inside + Y .* escaped;

                iter_map = iter_map + still_inside;
            end

            wait(gpuDevice);
            Times(repeat) = toc;
            iter_map_cpu = gather(iter_map);

            if repeat == iterations
                mandelbrot_plot(iter_map_cpu, i, max_iter, "Images_GPU", "");
            end
        end
        dataRows(result_row, :) = [{image_Size_Names(i)}, num2cell(Times)];
        result_row = result_row + 1;
    end

    output = [headers; dataRows];
    writecell(output, "GPU_Times.csv");
end