% =========================================================================
% Practical 2: Mandelbrot-Set Serial vs Parallel Analysis
% =========================================================================
%
% GROUP NUMBER:
%
% MEMBERS:
%   - Member 1 Name, Student Number
%   - Joab Kloppers, KLPJOA002

%% ========================================================================
%  PART 4: Testing and Analysis
%  ========================================================================
% Compare the performance of serial Mandelbrot set computation
% with parallel Mandelbrot set computation.

function run_analysis()
    %Array conatining all the image sizes to be tested
    image_sizes = [
        [800,600],   %SVGA
        [1280,720],  %HD
        [1920,1080], %Full HD
        [2048,1080], %2K Cinema
        [2560,1440], %2K QHD
        [3840,2160], %4K UHD
        [5120,2880], %5K
        [7680,4320]  %8K UHD
    ]

    max_iterations = 1000; 

    % Get number of workers available

    %fprintf("test")

    mandelbrot_plot(max_iterations,image_sizes);
    
    %TODO: For each image size, perform the following:
    %   a. Measure execution time of mandelbrot_serial
    %   b. Measure execution time of mandelbrot_parallel
    %   c. Store results (image size, time_serial, time_parallel, speedup)  
    %   d. Plot and save the Mandelbrot set images generated by both methods
    
end

%% ========================================================================
%  PART 1: Mandelbrot Set Image Plotting and Saving
%  ========================================================================
%
% TODO: Implement Mandelbrot set plotting and saving function
function mandelbrot_plot(max_iter,sizes) %Add necessary input arguments
     % --- Grid setup ---
    width    = sizes(3,1)
    height   = sizes(3,2)

    % Define the region of the complex plane to view
    x_range = linspace(-2.5, 1.0, width);   % Real axis
    y_range = linspace(-1.2, 1.2, height);  % Imaginary axis

    % Preallocate output image (each pixel = iteration count)
    iter_map = zeros(height, width);

    % --- Loop over every pixel ---
    for row = 1:height
        for col = 1:width
            x0 = x_range(col);
            y0 = y_range(row);

            x = 0;
            y = 0;
            iteration = 0;

            % Core Mandelbrot loop (from your pseudocode)
            while iteration < max_iter && (x^2 + y^2) <= 4
                x_next = x^2 - y^2 + x0;   % Note: NOT x^2+y^2 (see below)
                y_next = 2*x*y + y0;

                x = x_next;
                y = y_next;
                iteration = iteration + 1;
            end

            iter_map(row, col) = iteration;
        end
    end


    % --- Save to file instead of displaying ---
    % Normalize iter_map to [0, 255] for image output
    img_normalized = uint8(255 * iter_map / max_iter);
    
    % Apply a colormap (returns Nx3 RGB values)
    cmap = hot(256);
    img_rgb = ind2rgb(img_normalized, cmap);
    
    % Save to file
    imwrite(img_rgb, 'mandelbrot.png');
end

%% ========================================================================
%  PART 2: Serial Mandelbrot Set Computation
%  ========================================================================`
%
%TODO: Implement serial Mandelbrot set computation function
function mandelbrot_serial(varargin) %Add necessary input arguments 
    fprintf("Test1")
end

%% ========================================================================
%  PART 3: Parallel Mandelbrot Set Computation
%  ========================================================================
%
%TODO: Implement parallel Mandelbrot set computation function
function mandelbrot_parallel(varargin) %Add necessary input arguments 
    poolobj = gcp('nocreate');
    
     % Create a pool only if one doesn ' t exist
    if isempty(poolobj)
       parpool('local',N);
    end
    
    pool = gcp('nocreate');
    if isempty(pool)
        disp('No parallel pool active');
    else
        disp(['Parallel pool has ', num2str(pool.NumWorkers), ' workers']);
    end


    delete(gcp('nocreate'));
end

